[package]
name = "assignment_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.10.1"
num-bigint = "0.4.3"
num-traits = "0.2.14"